title: Kerun (Keri) Yu
description: A personal website currently under construction.
theme: jekyll-theme-minimal
logo: ./images/1712689889015.jpeg
linkedin: https://www.linkedin.com/in/keri-yu
github: https://github.com/KeriYuu

