title: Kerun (Keri) Yu
description: 
theme: jekyll-theme-minimal
logo: ./images/1712689889015.jpeg
email: kerunyuu@gmail.com

social_links:
  - platform: linkedin
    url: https://linkedin.com/in/keri-yu
  - platform: github
    url: https://github.com/KeriYuu

